### ISSUE TITLE
login change

### ISSUE THREAD

**Issue by diuna2000** [xt16johnny/HA-LeapCard#1]
Hi  leap card  change login page can you updated plese

**Comment by JXGA** [comment]
Sorry, missed this issue. 

This is due to the login-page changing, so the plugin is now useless. 

Unfortunately Leap still haven't provided a public API and they now use Microsoft to authenticate users on their site, so it's no longer a straightforward process. 

I'm going to close this issue as I now consider this project archived. 

Thanks
